### ISSUE TITLE
Slime blocks don't interact with pistons like in mc

### ISSUE THREAD

**Issue by anon55555** [kay27/MineClone2#4] opened 2020-10-01 11:16 UTC
See https://minecraft.gamepedia.com/Slime_Block#Pistons.

**Comment by kay27** [comment] 2020-10-04 09:50
Confirmed. I don't see slime-block-related stuff and there is even made a comment probably about it: https://github.com/kay27/MineClone2/blob/master/mods/ITEMS/REDSTONE/mesecons_mvps/init.lua#L60

I'll take a look whether it could be added easily and what will happen... I mean there's some delay in ticks in MC between the (inter)actions of flying machine's part :) IDK what/how it will be in Minetest

**Comment by kay27** [comment] 2020-10-04 20:30
Seems fixed, see https://github.com/kay27/MineClone2/commit/bf003241e355098c3d184d519be8f615bca433ab
Actually the fix is made in ```nodes_misc.lua```.
Changes in ```mesecons_mvps``` is almost useless...

But for now hadn't time to build flying machine and test... :((( Only tested that blocks do move with slimeblock as in MC.

**Comment by kay27** [comment] 2020-10-04 22:53
Actually I can't run a flying machine as it described [here](https://minecraft.gamepedia.com/Tutorials/Flying_machines).
Something moves but then it gets stuck,
Slime block behaves good. Probably something wrong with redstone block or the way the pistons get the power.
![image](https://user-images.githubusercontent.com/2028802/95029004-f4bff480-06b5-11eb-9c2d-473d9b55a99a.png)

**Comment by kay27** [comment] 2020-10-04 22:55
Also I must check the protection after fixing that.

**Comment by kay27** [comment] 2020-10-05 18:09
Much more simple example, looks like the piston is powered:
![image](https://user-images.githubusercontent.com/2028802/95115899-410f4100-0757-11eb-9f25-4ef204b95c4b.png)
Mesecon mod changed a lot since it was added to MCL2, e. g. added some LBM handlers but I just try to understand how the queue works :) I need some additional time for that.

**Comment by kay27** [comment] 2020-10-05 21:26
hm, btw in original mesecon/minetest_game it works, except that there's no redstone block...

https://github.com/kay27/MineClone2/blob/master/mods/ITEMS/REDSTONE/mesecons_mvps/init.lua#L277 looks redundant, duplicates by https://github.com/kay27/MineClone2/blob/master/mods/ITEMS/REDSTONE/mesecons_mvps/init.lua#L374

**Comment by kay27** [comment] 2020-10-06 06:00
@anon55555 I made next fix. Some mechanics started to work in a loop, back and forth. But I still can't run really flying machine. Maybe you'd like to test it and help me to understand what's wrong now? https://github.com/kay27/MineClone2/commit/70314622841df5717d913d3f1a1391c25110e145

**Comment by anon55555** [comment] 2020-10-06 15:25
I'm getting crashes with this error message: `attempt to index local 'pistonspec' (a nil value)`.

**Comment by kay27** [comment] 2020-10-07 19:41
So odd, couldn't you please specify the line number if you remember it? I had same error and added meta for avoiding but several places maybe need it too but seems it was wrong way at all... Pusher shouldn't power the piston... But then I cant realize what's going on in Minecraft: when the pusher looks up - if it has a contact with redstone block by one of it's sides it keeps pushed state...

So I merged slime blocks fix to master as Mesehub backed to life... There is a big issue about redstone mechanics:

https://git.minetest.land/Wuzzy/MineClone2/issues/353#issuecomment-11392

**Comment by kay27** [comment] 2020-10-08 18:59
I found an article explains some differences for myself, https://minecraft.gamepedia.com/Tutorials/Quasi-connectivity

Should it be implemented in MCL2? :))) IDK

**Comment by kay27** [comment] 2020-10-08 20:16
Wow, can't believe!
After this simple change (on the picture attached) mechanics started to move back and forth like in Minecraft! So it wasn't even a significant change - I just added: 1) debug output through the chat; 2) delays; 3) little bugfix in the passing two tables to outer threads. That's all...
Now I need to remove delays back and see what will happen and I'll do that later when I'll have the time for it.

![image](https://user-images.githubusercontent.com/2028802/95508713-7d93a480-09c4-11eb-9377-7fe3394d0cce.png)

**Comment by kay27** [comment] 2020-10-08 22:20
OMG, I was wrong again. The error was a duplicated addition of the vector in ```mvps_push_or_pull()```, I removed it, https://git.minetest.land/Wuzzy/MineClone2/commit/f0afebea387d6972d0f3820ea44913b6fbbe4f7c

This sample of mechanics started to work immediately :)

Then I tried to loop it to the piston from its back and redstone block disappeared - so maybe there are still some bugs left.

**Comment by kay27** [comment] 2020-10-08 22:21
By the way, maybe, we need to merge node timer patch from https://github.com/minetest-mods/mesecons/commit/42cd97392110993db6c19d9c8af2a468d72f2ab1#diff-fe45ad82229c80f9a7352e533b6c311a

**Comment by kay27** [comment] 2020-10-08 22:36
> Then I tried to loop it to the piston from its back and redstone block disappeared - so maybe there are still some bugs left.

Probably @Wuzzy2 already reported the bug here: https://github.com/minetest-mods/mesecons/issues/218#issuecomment-356408162

**Comment by kay27** [comment] 2020-10-08 23:24
The bug is because the piston loops to itself.
When I try to add distance check in piston's stopper it always affects itself too :)
And slime block's sticky function doesn't check the direction of adjacent piston as well...

The end.

I've wrote it to not forget to add piston direction check in any of the stopper checks... I think if slime block connects to the front part of the pusher it must just ignore this neighbor.

Every time I think: one more final step and I close the issue... But I'd like to fly and still can't fly on the machine... And the honey is missing too :(((

**Comment by kay27** [comment] 2020-10-10 22:39
There are still many bugs but:
1) Mesehub came back to life;
2) the subject is fixed;
3) fixed some major issues related.
I'm closing the issue.
See also:
https://github.com/kay27/MineClone2/commit/b0eecea7095ba4cd183ed91642a3deff767142a8
https://github.com/kay27/MineClone2/commit/0d96a439ea6c912bc669d56806df8b9bee805a08
https://github.com/minetest/minetest/issues/6981
https://git.minetest.land/Wuzzy/MineClone2/issues/839

**Closed as completed by kay27** 2020-10-10 22:39 UTC
Labels: bug
